import { useState } from 'react'
import QRcode from "qrcode"
import React from 'react'
import './qr.css'

function App() {
const [url,seturl]= useState("")
const [qr,setqr] = useState("")


const handle=(e)=>{
  seturl(e.target.value)
}

const generate=()=>{
  QRcode.toDataURL(url, {
    color: {
      dark: "#000000", // Foreground (QR dots)
      light: "#ffffff" // Background
    }
  },(err,url)=>{
  if (err) return console.error(err);
  console.log(url);
  setqr(url)
})
}
  return (
    <>
    <h2>Qr-Code-Genertor:</h2>
      <div className='rish'>
        <div> <input type="search" placeholder='Type your url' value={url} onChange={handle} onKeyDown={(e) => {
    if (e.key === 'Enter') generate();
  }}/>
        <button onClick={generate} disabled={!url.trim()}>Generate</button></div>
      {
        qr && <>
      <img src={qr} alt="Qr" title='Qr-code generated by Rishabh sharma' />
      <a href={qr} download="qr.png">Download</a>
        </>
      }
      </div>
    </>
  );
}

export default App
